import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Footer from './components/Footer'
import Header from './components/Header'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tic Tac Toe',
  description: 'Generated by create next app',
  creator: 'Luciano Rodríguez'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} flex flex-col min-h-screen`}>
        <Header />
        <main className="flex-grow max-w-screen-md m-auto flex items-center justify-center">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
